[package]
name = "roxi"
version = "0.1.0"
authors = ["mal0ner <cameronmkm2@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"     # error handling
bytes = "1.7.1"       # helps manage buffers
lazy_static = "1.5.0"
thiserror = "1.0.63"  # error handling
